"use client";
import React, { useState, useEffect } from "react";
import { Inter } from "next/font/google";
// import { Metadata } from 'next';
import Navbar from "@/components/Navbar";
import { SplashScreen } from "@/components/SplashScreen";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 5000);
  }, []);

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
          {/* <Navbar /> */}
          {loading ? (
            <div className={`splash ${loading ? "fade-out" : ""}`}>
              <SplashScreen />
            </div>
          ) : (
            children
          )}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
